customhost = "employee.cqymwpppbx79.ap-south-1.rds.amazonaws.com"
customuser = "intellipaat"
custompass = "intellipaat123"
customdb = "employee"
custombucket = "employeecollection"
customregion = "us-east-2"
