customhost = "employee.cqymwpppbx79.ap-south-1.rds.amazonaws.com"
customuser = "admin"
custompass = "Password123$$"
customdb = "employee"
custombucket = "employeecollection"
customregion = "ap-south-1a"
